default:
    trainer: ppo
    batch_size: 1024
    beta: 5.0e-3
    buffer_size: 10240
    epsilon: 0.2
    hidden_units: 128
    lambd: 0.95
    learning_rate: 3.0e-4
    max_steps: 5.0e4
    memory_size: 256
    normalize: false
    num_epoch: 3
    num_layers: 2
    time_horizon: 64
    sequence_length: 64
    summary_freq: 1000
    use_recurrent: false
    vis_encode_type: simple
    reward_signals: 
        extrinsic:
            strength: 1.0
            gamma: 0.99

Sandman:
    normalize: false
    batch_size: 2560
    buffer_size: 25600
    summary_freq: 1000
    time_horizon: 1000
    sequence_length: 64
    learning_rate: 1.0e-5
    lambd: 0.95
    beta: 1e-3
    use_recurrent: false
    use_curiosity: true
    max_steps: 1.0e7
    hidden_units: 1024
    num_layers: 3
    num_epoch: 2
    reward_signals:
        extrinsic:
            strength: 1.0
            gamma: 0.9
        curiosity:
            strength: 0.02
            gamma: 0.99
            encoding_size: 256

Ariadne:
    normalize: false
    batch_size: 1024
    buffer_size: 25600
    summary_freq: 1000
    time_horizon: 1000
    sequence_length: 64
    learning_rate: 1.0e-4
    lambd: 0.95
    beta: 1e-3
    use_recurrent: false
    use_curiosity: true
    max_steps: 1.0e7
    hidden_units: 32
    num_layers: 2
    num_epoch: 3
    reward_signals:
        extrinsic:
            strength: 1.0
            gamma: 0.8
        curiosity:
            strength: 0.05
            gamma: 0.99
            encoding_size: 256